name: Build Windows

on:
  workflow_call:

env:
  CMAKE_PRESET: Windows

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetches all history
          fetch-tags: true # explicitly fetches tags
          submodules: true

      - name: CMake Configure
        run: cmake --preset=${CMAKE_PRESET}

      - name: CMake Workflow
        run: cmake --workflow --preset=${CMAKE_PRESET}

      - name: Upload devel tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: devel-tarball
          path: _bld-${CMAKE_PRESET}/${{ github.event.repository.name }}*-devel.tar.xz
