name: Build Windows

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetches all history
          fetch-tags: true # explicitly fetches tags
          submodules: true

      - name: CMake Configure
        run: cmake --preset=Windows

      - name: CMake Workflow
        run: cmake --workflow --preset=Windows
